.TH LIBCFARMHASH 3 "JANUARY 2015" "libcfarmhash-0.1.0" "Farmhash C port"
.SH NAME

C port of the Farmhash Hash64 (farmhashna) hash function

.SH SYNOPSIS

#include <cfarmhash.h>

uint64_t cfarmhash(const char *, size_t);

.SH DESCRIPTION

Hash function for a byte array. May change from time to time, may differ on different platforms.

.SH AUTHOR

Fredrik Widlund <fredrik dot widlund at gmail dot com>

